/* Auditoria frontend-design: telas em 1440 e 390 × 2 temas. */
import { chromium, devices } from 'playwright'

const BASE = 'http://localhost:5173'
const browser = await chromium.launch()
const shot = async (p: import('playwright').Page, name: string) =>
  p.screenshot({ path: `/tmp/fd-${name}.png` })

/* seed desktop */
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } })
const p = await ctx.newPage()
p.on('pageerror', e => console.log('PAGE-ERR:', String(e).slice(0, 200)))

await p.goto(`${BASE}/`, { waitUntil: 'networkidle' })

await p.getByLabel('Nova etiqueta').click()
await p.waitForTimeout(200)
await p.keyboard.type('urgente')
await p.getByLabel('Cor Red').click()
await p.getByRole('button', { name: 'Criar etiqueta' }).click()
await p.waitForTimeout(200)
await p.getByLabel('Novo projeto').click()
await p.waitForTimeout(200)
await p.keyboard.type('Tarefas Empresa')
await p.getByRole('button', { name: 'Criar projeto' }).click()
await p.waitForTimeout(300)
await p.getByText('Adicionar seção').last().click()
await p.keyboard.type('Em andamento')
await p.keyboard.press('Enter')
await p.waitForTimeout(150)
await p.locator('section').getByText('Adicionar tarefa').click()
await p.keyboard.type('Edson / Chefware p2 @urgente')
await p.keyboard.press('Enter')
await p.keyboard.press('Escape')
await p.waitForTimeout(150)

await p.goto(`${BASE}/`, { waitUntil: 'networkidle' })
await p.getByText('Adicionar tarefa').first().click()
await p.keyboard.type('Cobrar cliente Patrícia hoje p1')
await p.keyboard.press('Enter')
await p.keyboard.type('Revisar pedido EMBALA amanhã 14h p2')
await p.keyboard.press('Enter')
await p.keyboard.type('Planejar trimestre p3')
await p.keyboard.press('Enter')
await p.keyboard.type('Sem nada definido')
await p.keyboard.press('Enter')
await p.keyboard.press('Escape')
await p.waitForTimeout(200)

await p.getByText('Planejar trimestre').click()
await p.waitForTimeout(300)
const dlg = p.getByRole('dialog')
await dlg.getByPlaceholder('Adicionar descrição...').fill('Separar metas por área e revisar orçamento.')
await dlg.getByText('Adicionar sub-tarefa').click()
await p.keyboard.type('Mapear metas')
await p.keyboard.press('Enter')
await p.keyboard.type('Reunir números')
await p.keyboard.press('Enter')
await p.keyboard.press('Escape')
await p.keyboard.press('Escape')
await p.waitForTimeout(200)
await p.getByText('Cobrar cliente').click()
await p.waitForTimeout(300)
const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10)
await p.getByRole('dialog').getByRole('button', { name: /Hoje/ }).click()
await p.waitForTimeout(150)
await p.locator('input[type="date"]').fill(yesterday)
await p.keyboard.press('Escape')
await p.keyboard.press('Escape')
await p.waitForTimeout(200)
await p.locator('[role="checkbox"]').last().click()
await p.waitForTimeout(400)

for (const theme of ['light', 'dark'] as const) {
  await p.evaluate(t => localStorage.setItem('theme', t), theme)
  await p.goto(`${BASE}/`, { waitUntil: 'networkidle' })
  await shot(p, `1440-${theme}-inbox`)
  await p.goto(`${BASE}/hoje`, { waitUntil: 'networkidle' })
  await shot(p, `1440-${theme}-hoje`)
  await p.goto(`${BASE}/em-breve`, { waitUntil: 'networkidle' })
  await shot(p, `1440-${theme}-embreve`)
  await p.locator('aside').getByText('Tarefas Empresa').click()
  await p.waitForTimeout(300)
  await shot(p, `1440-${theme}-projeto`)
  await p.locator('aside').getByText('urgente').click()
  await p.waitForTimeout(300)
  await shot(p, `1440-${theme}-etiqueta`)
  await p.goto(`${BASE}/filtros`, { waitUntil: 'networkidle' })
  await shot(p, `1440-${theme}-filtros`)
  await p.goto(`${BASE}/`, { waitUntil: 'networkidle' })
  await p.getByText('Planejar trimestre').click()
  await p.waitForTimeout(350)
  await shot(p, `1440-${theme}-detalhe`)
  await p.keyboard.press('Escape')
  await p.waitForTimeout(200)
  await p.keyboard.press('Meta+k')
  await p.waitForTimeout(250)
  await shot(p, `1440-${theme}-paleta`)
  await p.keyboard.press('Escape')
  await p.waitForTimeout(150)
}
await ctx.close()

/* mobile 390 */
const mctx = await browser.newContext(devices['iPhone 13'])
const m = await mctx.newPage()
m.on('pageerror', e => console.log('PAGE-ERR-M:', String(e).slice(0, 200)))

await m.goto(`${BASE}/`, { waitUntil: 'networkidle' })
await m.getByText('Adicionar tarefa').first().tap()
await m.waitForTimeout(350)
await m.keyboard.type('Cobrar cliente hoje p1')
await m.getByLabel('Adicionar tarefa').last().tap()
await m.waitForTimeout(200)
await m.keyboard.type('Revisar pedido amanhã p2')
await m.getByLabel('Adicionar tarefa').last().tap()
await m.waitForTimeout(200)
await m.keyboard.press('Escape')
await m.waitForTimeout(300)

for (const theme of ['light', 'dark'] as const) {
  await m.evaluate(t => localStorage.setItem('theme', t), theme)
  await m.goto(`${BASE}/`, { waitUntil: 'networkidle' })
  await shot(m, `390-${theme}-inbox`)
  await m.goto(`${BASE}/hoje`, { waitUntil: 'networkidle' })
  await shot(m, `390-${theme}-hoje`)
  await m.goto(`${BASE}/em-breve`, { waitUntil: 'networkidle' })
  await shot(m, `390-${theme}-embreve`)
  await m.goto(`${BASE}/navegar`, { waitUntil: 'networkidle' })
  await shot(m, `390-${theme}-navegar`)
  await m.goto(`${BASE}/filtros`, { waitUntil: 'networkidle' })
  await shot(m, `390-${theme}-filtros`)
  await m.goto(`${BASE}/`, { waitUntil: 'networkidle' })
  await m.getByText('Cobrar cliente').tap()
  await m.waitForTimeout(450)
  await shot(m, `390-${theme}-detalhe`)
  await m.getByLabel('Fechar').tap()
  await m.waitForTimeout(250)
}
await mctx.close()

/* estados vazios */
const ectx = await browser.newContext({ viewport: { width: 1440, height: 900 } })
const e = await ectx.newPage()

await e.goto(`${BASE}/hoje`, { waitUntil: 'networkidle' })
await shot(e, 'vazio-hoje')
await e.goto(`${BASE}/em-breve`, { waitUntil: 'networkidle' })
await shot(e, 'vazio-embreve')
await e.goto(`${BASE}/`, { waitUntil: 'networkidle' })
await shot(e, 'vazio-inbox')
await ectx.close()

await browser.close()
console.log('ok')
